// Pure version-consistency checker (#79). The manifest (package.json) is the
// single source of truth; every other version surface the project stores is
// compared against it. No I/O here — the CLI wrapper
// (src/scripts/check-version-consistency.ts) gathers the real surfaces and feeds
// them in, which keeps the comparison logic trivially unit-testable.
//
// A "surface" is a version WRITTEN DOWN somewhere a person or a gate reads it
// back. Two of them are derived rather than hand-typed, and they do not behave
// alike (#538):
//
//  - `runtime` is `appVersion`, which reads package.json at module load. In the
//    CLI it therefore cannot disagree with `manifest`. It earns its place as a
//    pure axis, not as a drift detector.
//  - `openapi` is a COMMITTED artifact, regenerated by `openapi:export`. It goes
//    stale the moment the manifest is bumped without a re-export, which is why a
//    release commit carries openapi.json alongside the other three files.
//
// So `openapi` is the one derived surface that genuinely drifts. CI already
// catches a stale spec under `publish.yml`'s "OpenAPI freshness" step, but that
// name says nothing about versions, and every release had to explain the
// connection in prose. Checking it here moves the failure to pre-commit, under a
// message that names the version.

export interface VersionSurfaces {
  /** package.json version — the source of truth all others are compared against. */
  manifest: string;
  /** package-lock.json version. */
  lockfile: string;
  /** First dated `## [X.Y.Z]` heading in CHANGELOG.md (null when none found). */
  changelogTop?: string | null;
  /** API runtime version (src/lib/version.ts appVersion). */
  runtime?: string;
  /** `info.version` in the committed openapi.json (#538). */
  openapi?: string;
  /** Latest `vX.Y.Z` git tag, v-prefix stripped (null when no tags). */
  latestTag?: string | null;
}

export interface VersionMismatch {
  surface: string;
  expected: string;
  actual: string;
}

export interface CheckOptions {
  /** Enforce the git-tag axis. Off by default — a release bump commit
   *  legitimately runs ahead of the tag, so the tag is only checked on
   *  tag/release events in CI, never on every commit. */
  checkTag?: boolean;
}

export function checkVersionConsistency(
  surfaces: VersionSurfaces,
  opts: CheckOptions = {}
): VersionMismatch[] {
  const { manifest, lockfile, changelogTop, runtime, openapi, latestTag } =
    surfaces;
  const mismatches: VersionMismatch[] = [];

  const compare = (surface: string, actual: string | null | undefined) => {
    if (actual != null && actual !== manifest) {
      mismatches.push({ surface, expected: manifest, actual });
    }
  };

  compare('lockfile', lockfile);
  compare('changelog', changelogTop);
  compare('runtime', runtime);
  compare('openapi', openapi);
  if (opts.checkTag) {
    compare('tag', latestTag);
  }

  return mismatches;
}
